### ISSUE TITLE
Bugs when parsing pdf

### ISSUE THREAD

**Issue by chenzhutian** [kmpoon/hlta#9]
When I feed in some pdfs, it shows me bug logs as below:
<img width="1225" alt="image" src="https://user-images.githubusercontent.com/3315274/47154184-e36f5900-d2e1-11e8-86bf-af840ba0342e.png">

How can I fix it?
Just let me know if any further information is needed

**Comment by kmpoon** [comment]
This seems to be a problem related to the PDF parser but not the HLTA.

According to the page below, the problem seems to be that there is a large PDF file:

https://stackoverflow.com/questions/22946079/pdfbox-loading-large-files

You may perhaps try to change the system property ```org.apache.pdfbox.baseParser.pushBackSize``` to a large value as follows:

http://www.java2s.com/Tutorial/Java/0120__Development/SettingtheValueofaSystemPropertyfromtheCommandLineaddDoptiontothejavacommandwhenrunningyourprogram.htm

**Comment by jelif** [comment]
One of the answer in stackoverflow said "that parser (which will be the only one in the upcoming 2.0 version) is independent of the size of a pushback buffer". I have released a new version of HLTA that uses pdfbox 2.0. Hopefully the issue could be solved.
